project:
  group: laplacian
  name: domain-model.document-template
  type: template
  namespace: laplacian
  version: '1.0.0'
  description:
    en: |
      This template generates diagrams that represents the structure of schemas
      defined by the [Metamodel](https://github.com/nabla-squared/laplacian.model.metamodel).
    ja: |
      This template generates diagrams that represents the structure of schemas
      defined by the [Metamodel](https://github.com/nabla-squared/laplacian.model.metamodel).
    zh: |
      This template generates diagrams that represents the structure of schemas
      defined by the [Metamodel](https://github.com/nabla-squared/laplacian.model.metamodel).
  source_repository:
    url: https://github.com/nabla-squared/laplacian.domain-model.document-template.git
    branch: master
  template-files:
  - dest/
