project:
  group: laplacian
  name: schema.document-template
  type: template
  namespace: laplacian
  version: '1.0.0'
  description: |
    This template generates diagrams that represents the structure of schemas
    defined by the [Metamodel](https://github.com/nabla-squared/laplacian.model.metamodel).
  source_repository:
    url: https://github.com/nabla-squared/laplacian.schema.document-template.git
    branch: master
