project:
  sources:
  - "README.md"
  - ".editorconfig"
  - ".gitattributes"
  - ".gitignore"
  - "gradlew"
  - "model/project/sources.yaml"
  - "model/project.yaml"
  - "src/doc/entities/{each entities.in_namespace as entity}{entity.class_name}.md.hbs"
  - "src/doc/image/model-diagram.puml.hbs"
